# Generated by Django 5.2.8 on 2025-11-30 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StateType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "State Type",
                "verbose_name_plural": "State Types",
                "db_table": "state_types",
            },
        ),
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("language_code", models.CharField(default="ru", max_length=10)),
                ("subscription_active", models.BooleanField(default=False)),
                (
                    "subscription_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатная"),
                            ("basic", "Базовая"),
                            ("premium", "Премиум"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_blocked", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram профиль",
                "verbose_name_plural": "Telegram профили",
                "db_table": "telegram_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserState",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_states",
                        to="bot.statetype",
                    ),
                ),
                (
                    "telegram_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="bot.telegramprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User State",
                "verbose_name_plural": "User States",
                "db_table": "user_states",
                "indexes": [
                    models.Index(
                        fields=["telegram_profile", "state_type"],
                        name="ix_user_states_profile_type",
                    ),
                    models.Index(fields=["created_at"], name="ix_user_states_created"),
                ],
            },
        ),
    ]
