# Generated by Django 5.2.8 on 2025-11-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="last_request_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
