# Generated by Django 5.2.8 on 2025-12-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_telegramprofile_last_request_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код тарифа"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена (₽)"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(verbose_name="Продолжительность (дни)"),
                ),
                (
                    "daily_sessions_limit",
                    models.IntegerField(verbose_name="Лимит сессий в день"),
                ),
                (
                    "cards_limit",
                    models.IntegerField(verbose_name="Количество доступных карт"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тариф подписки",
                "verbose_name_plural": "Тарифы подписок",
                "db_table": "subscriptions",
                "ordering": ["price"],
            },
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатная"),
                    ("basic", "Базовая"),
                    ("premium", "Премиум"),
                ],
                default="free",
                help_text="Deprecated: используйте current_subscription",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="current_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="bot.subscription",
                verbose_name="Текущая подписка",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID заказа"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ID платежа"
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID подписки Prodamus",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("success", "Успешно оплачено"),
                            ("failed", "Ошибка оплаты"),
                            ("cancelled", "Отменено"),
                            ("refunded", "Возвращено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email клиента",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Телефон клиента",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено"
                    ),
                ),
                (
                    "webhook_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Данные webhook"
                    ),
                ),
                (
                    "telegram_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bot.telegramprofile",
                        verbose_name="Telegram профиль",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bot.subscription",
                        verbose_name="Тарифный план",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order_id"], name="ix_payments_order_id"),
                    models.Index(
                        fields=["telegram_profile", "status"],
                        name="ix_payments_profile_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало сессии"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение сессии"
                    ),
                ),
                ("request_text", models.TextField(verbose_name="Текст запроса")),
                (
                    "request_type",
                    models.CharField(max_length=50, verbose_name="Тип запроса"),
                ),
                (
                    "card_type",
                    models.CharField(max_length=20, verbose_name="Тип карты"),
                ),
                ("card_number", models.IntegerField(verbose_name="Номер карты")),
                (
                    "telegram_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bot.telegramprofile",
                        verbose_name="Telegram профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия пользователя",
                "verbose_name_plural": "Сессии пользователей",
                "db_table": "user_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_profile", "started_at"],
                        name="ix_sessions_profile_start",
                    ),
                    models.Index(fields=["started_at"], name="ix_sessions_started"),
                ],
            },
        ),
    ]
