# Generated by Django 5.2.8 on 2025-12-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_subscription_alter_telegramprofile_subscription_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramprofile",
            name="subscription_type",
        ),
    ]
