# Generated by Django 5.2.8 on 2025-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_remove_telegramprofile_subscription_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramprofile",
            name="subscription_active",
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Подписка до"
            ),
        ),
    ]
