# Generated by Django 5.2.8 on 2025-12-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_remove_telegramprofile_subscription_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="bot.subscription",
                verbose_name="Тарифный план",
            ),
        ),
    ]
