# Generated by Django 5.2.8 on 2025-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_alter_payment_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="cards_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество доступных карт"
            ),
        ),
    ]
