# Generated by Django 5.2.8 on 2025-12-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_alter_subscription_cards_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название тарифа"),
        ),
    ]
