# Generated by Django 5.2.8 on 2025-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_increase_subscription_name_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="prodamus_subscription_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID подписки из личного кабинета Prodamus для рекуррентных платежей",
                null=True,
                verbose_name="ID подписки в Prodamus",
            ),
        ),
    ]
