# Generated by Django 5.2.8 on 2026-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_subscription_prodamus_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email для отправки чеков платежной системой",
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
    ]
