# Generated by Django 5.2.8 on 2026-07-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0010_add_email_to_telegram_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Подсистема"
                    ),
                ),
                ("beat_at", models.DateTimeField(verbose_name="Время пульса")),
            ],
            options={
                "verbose_name": "Пульс бота",
                "verbose_name_plural": "Пульс бота",
                "db_table": "bot_heartbeats",
            },
        ),
    ]
